---
- name: Install and run mongodb
  hosts: all
  become: true

  roles:
    - db
#  tasks:
#  # Добавим ключ репозитория для последующей работы с ним
#  - name: Add APT key
#    apt_key:
#      url: https://www.mongodb.org/static/pgp/server-4.2.asc
#      state: present
#
#  - name: Add repository
#    apt_repository:
#      repo: 'deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse'
#      state: present
#
#  - name: Install packages
#    apt:
#      name: mongodb-org
#      state: present
#      update_cache: true
#
#  - name: Configure service supervisor
#    systemd:
#      name: mongod
#      enabled: yes
